const mongoose = require('mongoose');

const enquirySchema = new mongoose.Schema({
  enquiryId: { type: String, required: true, unique: true },
  teamMember: String,
  customerName: String,
  companyDetails: String,
  address: String,
  city: String,
  state: String,  
  pincode: String,
  customerPhone: String,
  customerEmail: String,
  busType: String,
  otherBusType: String,
  featureRequirement: String,
  acPreference: String,
  chassisBought: String,
  chassisPurchaseTime: String,
  chassisCompanyName: String,
  chassisModel: String,
  wheelBase: String,
  tyreSize: String,
  length: String,
  width: String,
  seatingPattern: String,
  numberOfSeats: String,
  additionalNote: String,
  referralSource: String,

  // --- Business Details ---
  businessTypeOfBuses: String,
  businessNumberOfBuses: Number,
  businessPreviousBodyBuilder: String,
  businessBusesPerYear: Number,
  businessEmployees: Number,
  businessExpertiseArea: String,

  // --- Personal ---
  education: String,
  hobbies: String,
  behavior: String,
  customerType: {
    type: String,
    enum: ['Amazing', 'Bread winning', 'Convenience', 'Dangerous'],
  },

  // --- Luxury/Customization ---
  windowType: String,
  requiredNoEachSide: String,
  tintOfShades: String,
  otherTint: String,
  totalSeats: String,
  seatType: String,
  seatBelt: String,
  seatBeltType: String,
  seatMaterial: String,
  curtain: String,
  flooringType: String,
  passengerDoors: String,
  passengerDoorPosition: String,
  doorType: String,
  roofCarrier: String,
  diggyType: String,
  sideLuggageReq: String,
  diggyFlooring: String,
  sideLadder: String,
  helperFootStep: String,
  rearBackJaal: String,
  cabinType: String,
  specificRequirement: String,
  suggestedModel: String,

  optionalFeatures: [String],
  fitmentProvided: [String],

  pdfData: Buffer, 
  createdAt: { type: Date, default: Date.now },
  lead: { type: mongoose.Schema.Types.ObjectId, ref: 'Lead' },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
});

module.exports = mongoose.model('Enquiry', enquirySchema);
